swagger: '2.0'
info:
  description: "Auth microservice - BankingX"
  version: "1.0.0"
  title: "Authentication API"
host: "www.bank.com"
schemes:
  - "http"
paths:
  /auth/signup:
    post:
      summary: "Register a new user"
      description: "Create a new user account by providing required details."
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: users
          description: "User information to be registered"
          required: true
          schema:
            type: object
            required:
              - username
              - email
              - password
            properties:
              username:
                type: string
                example: "username"
              email:
                type: string
                example: "user@example.com"
              password:
                type: string
                example: "password123"
      responses:
        200:
          description: "User successfully created"
          headers:
            Authorization:
              description: "JWT token used for subsequent authenticated requests."
              type: string
          schema:
            type: object
            properties:
              successfuly:
                type: boolean
                example: true
        400:
          description: "Bad request, invalid user data."
        409:
          description: "Conflict, user already exists."

  /auth/signin:
    post:
      summary: "Authenticate a user"
      description: "Login with email and password to receive a JWT token."
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: users
          description: "User credentials for login"
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                example: "user@example.com"
              password:
                type: string
                example: "password123"
      responses:
        200:
          description: "Authentication successful, JWT returned."
          headers:
            Authorization:
              description: "JWT token used for subsequent authenticated requests."
              type: string
          schema:
            type: object
            properties:
              successfuly:
                type: boolean
                example: true
        400:
          description: "Bad request, invalid user data."
